openapi: 3.0.1
info:
  title: ITMOptics
  description: API for ITMO history project
  version: 1.0.1

servers:
  - url: /api/v1
tags:
  - name: Exhibits
    description: Simple exhibit endpoints
  - name: Specification
    description: The swagger API specification

paths:
  /exhibits:
    get:
      tags:
        - Exhibits
      summary: Fetch all exhibits
      description: Fetch all exhibits
      responses:
        200:
          description: Returns all exhibits
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exhibits'
              example:
                - id: 1
                  title: Bla
                  text: Lorem ipsum...
                  image: https://i.redd.it/tospo6k2u9l81.png
                  createdAt: "2022-11-27T16:10:26.507Z"
                  updatedAt: "2022-11-27T16:10:26.507Z"
                - id: 4
                  title: Hasta la vista, baby
                  text: I need your clothes, your boots and your motorcycle.
                  image: https://i.redd.it/tospo6k2u9l81.png
                  createdAt: "1984-10-26T11:40:24.007Z"
                  updatedAt: "1991-12-25T19:00:21.155Z"
    post:
      tags:
        - Exhibits
      summary: Adds a new exhibit
      description: Create a new exhibit
      parameters:
        - name: password
          in: query
          description: Admin password
          required: true
          schema:
            type: string
            example: Qwerty123

      requestBody:
        description: an exhibit
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExhibitBody"
            example:
              title: New amazing Exhibit
              text: bla-bla-bla
              image: https://i.redd.it/tospo6k2u9l81.png
        required: true

      responses:
        201:
          description: Exhibit created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exhibit'
              example:
                id: 1
                title: New amazing Exhibit
                text: bla-bla-bla. Created just now
                image: https://i.redd.it/tospo6k2u9l81.png
                createdAt: "2022-12-03T16:10:26.507Z"
                updatedAt: "2022-12-03T16:10:26.507Z"
        401:
          description: You're not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                errors:
                  - message: You're not authenticated

  /exhibits/{id}:
    get:
      tags:
        - Exhibits
      summary: Fetch exhibit by id
      description: Fetch exhibit by id
      parameters:
        - name: id
          in: path
          description: The id of the exhibit to retrieve
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Return the exhibit with the specified id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exhibit'
              example:
                id: 1
                title: Lorem ipsum dolor sit amet
                text: Vivamus vitae lorem velit. Maecenas finibus consectetur viverra.
                image: https://i.redd.it/tospo6k2u9l81.png
                createdAt: "2022-12-03T16:10:26.507Z"
                updatedAt: "2022-12-03T16:10:26.507Z"
        404:
          description: Exhibit not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                errors:
                  - message: Exhibit not found

    delete:
      tags:
        - Exhibits
      summary: Destroy an exhibit by id
      description: Destroy an exhibit
      parameters:
        - name: id
          in: path
          description: The id of the exhibit to destroy
          required: true
          schema:
            type: integer
            example: 1
        - name: password
          in: query
          description: Admin password
          required: true
          schema:
            type: string
            example: Qwerty123
      responses:
        200:
          description: Exhibit successfully destroyed
        401:
          description: You're not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                errors:
                  - message: You're not authenticated
        409:
          description: Exhibit cannot be destroyed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                errors:
                  - message: Exhibit cannot be destroyed
  /spec:
    get:
      tags:
        - Specification
      summary: OpenAPI specification of ITMOptics API
      description: OpenAPI specification of ITMOptics API
      responses:
        200:
          description: Return the API specification
          content: {}

components:
  schemas:
    Exhibit:
      title: Exhibit
      required:
        - id
        - title
        - text
        - image
        - createdAt
        - updatedAt
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        text:
          type: string
        image:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string

    Exhibits:
      type: array
      items:
        $ref: '#/components/schemas/Exhibit'

    ExhibitBody:
      title: Exhibit Body
      required:
        - title
        - text
        - image
      type: object
      properties:
        title:
          type: string
        text:
          type: string
        image:
          type: string

    Error:
      title: Error
      required:
        - errors
      type: object
      properties:
        errors:
          type: array
          items:
            type: object
            required:
              - message
            properties:
              message:
                type: string
